# Generated by Django 5.2.7 on 2025-10-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_pubg'),
    ]

    operations = [
        migrations.CreateModel(
            name='UCOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=50)),
                ('server', models.CharField(choices=[('asia', 'Asia'), ('europe', 'Europe'), ('north-america', 'North America'), ('south-america', 'South America'), ('middle-east', 'Middle East')], max_length=20)),
                ('uc_amount', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('terms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Pubg',
        ),
    ]
