# Generated by Django 5.2.7 on 2025-10-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_ucorder_delete_pubg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ucorder',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ucorder',
            name='server',
            field=models.CharField(max_length=20),
        ),
    ]
