# Generated by Django 5.2.7 on 2025-11-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_capturedimage_capturedvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tizim Logi',
                'verbose_name_plural': 'Tizim Loglari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='capturedimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rasm', 'verbose_name_plural': 'Rasmlar'},
        ),
        migrations.AlterModelOptions(
            name='capturedvideo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Video', 'verbose_name_plural': 'Videolar'},
        ),
        migrations.AddField(
            model_name='capturedimage',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='capturedvideo',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='capturedvideo',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
